# This recipe doesn't work on Python 3.9 (due to setuptools_scm issues),
# or on Python 3.8 (due to numpy availability issues)
package:
  name: matplotlib
  version: 3.6.0

patches:
  - setupext.patch
{% if py_version < (3, 11) %}
  # This is required because of the inconsistency in old Apple Support versions
  # in the error raised when subprocess is used.
  - subprocess.patch
{% endif %}

requirements:
  host:
    - freetype 2.9.1
    - libpng 1.6.34
    - numpy 1.26.0

  build:
    - certifi
    - setuptools_scm
