package:
  name: numpy
  version: 1.26.2

{% if version and version < (1, 26) %}
{% else %}

patches:
  - mobile-1.26.0.patch

requirements:
  host:
#     - chaquopy-openblas 0.2.20
#     - chaquopy-libgfortran 4.9  # Required by ld.bfd on arm64 (see build-wheel.py)
    - ninja
{% endif %}
