package:
  name: cryptography
  # This is the last version that didn't require Rust compilation.
  version: 3.4.8
  # version: 42.0.8

# version is only a jinja variable if there's an override;
# this first branch is the default (for now).
{% if not version or version <= (3, 4, 8) %}

patches:
  - random.patch

build:
  script_env:
    - CRYPTOGRAPHY_DONT_BUILD_RUST=1

requirements:
  build:
    - cffi
    - setuptools-rust
  host:
    - openssl 1.1.1

{% elif version and version[0] < 43 %}

requirements:
  build:
    - cffi
    - setuptools-rust
  host:
    - openssl 3.0.14

{% else %}
# cryptography 43.0.0 switched to maturin as a build backend.
# This config doesn't work yet, because we haven't got an iOS-patched maturin.
requirements:
  build:
    - cffi
    - maturin
  host:
    - openssl 3.0.14

{% endif %}
