package:
  name: libjpeg
  version: 1.5.3

source:
  url: https://downloads.sourceforge.net/project/libjpeg-turbo/{version}/libjpeg-turbo-{version}.tar.gz

patches:
  - config.patch

build:
  number: 1
